const Home = () => {
  return (
    <div className="">
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
      <h1>This is the Landing Page</h1>
    </div>
  );
};

export default Home;
